---
- name: Install OpenLDAP
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Create LDIF file
    copy:
      dest: /etc/ldap/tls/import.ldif
      content: |
        dn: cn=config
        changetype: modify
        replace: olcTLSCertificateKeyFile
        olcTLSCACertificateKeyFile: /etc/ldap/tls/ca-certificates.crt
        -
        replace: olcTLSCertificateKeyFile
        olcTLSCertificateKeyFile: /etc/ldap/tls/ldap.{{ ansible_hostname }}.{{ ansible_domain }}.key
        -
        replace: olcTLSCertificateFile
        olcTLSCertificateFile: /etc/ldap/tls/ldap.{{ ansible_hostname }}.{{ ansible_domain }}.crt
      owner: openldap
      group: openldap

  - name: Import configuration
    shell:
      cmd: ldapmodify -Y EXTERNAL -H ldapi:/// -f import.ldif
      chdir: /etc/ldap/tls/
