---
- name: Configure Static IP
  hosts: localhost
  connection: local
  become: true

  # Customize the variable values or use --extra-vars when running to override.
  # For example:
  #   vars:
  #     ip: 192.168.1.100
  #     gateway: 192.168.1.1
  #
  # Or specify on the command-line:
  #   ansible-playbook --extra-vars ip=192.168.1.100 --extra-vars gateway=192.168.1.1
  vars:
    ip: "{{ ansible_default_ipv4.address }}"
    mask: "{{ ansible_default_ipv4.netmask }}"
    gateway: "{{ ansible_default_ipv4.gateway }}"
    primary_dns: "{{ ansible_dns.nameservers[0] }}"

  tasks:
  - name: Check variables
    debug:
      msg: "The IP address hasn't changed. (Still using: {{ ip }}) Are you sure you don't want to customize using --extra-vars?"
    when: ip == ansible_default_ipv4.address

  - name: Configure network interface parameters
    copy:
      dest: /etc/network/interfaces.d/eth0
      content: |
        auto eth0
        allow-hotplug eth0
        iface eth0 inet static
        address {{ ip }}
        netmask {{ mask }}
        gateway {{ gateway }}
        dns-nameservers {{ primary_dns }}
        dns-search {{ ansible_domain }}

  - name: Disable DHCP
    service:
      name: dhcpcd
      state: stopped
      enabled: no

  - name: Reboot to active changes
    debug:
      msg: You must reboot for changes to take effect.
