---
- name: Configure Hostname
  hosts: localhost
  connection: local
  become: true

  # Customize the variable values or use --extra-vars when running to override.
  # For example:
  #   vars:
  #     host: raspberrypi
  #     domain: home
  #
  # Or specify on the command-line:
  #   ansible-playbook --extra-vars host=raspberrypi --extra-vars domain=home

  vars:
    host: "{{ ansible_hostname }}"
    domain: "{{ ansible_domain }}"

  tasks:
  - name: Check variables
    debug:
      msg: "Host and domain haven't changed. (Still using: {{ host }}.{{ domain }}) Are you sure you don't want to customize using --extravars?"
    when: host == ansible_hostname and domain == ansible_domain

  - name: Set the hostname
    ansible.builtin.hostname:
      name: "{{ host }}.{{ domain }}"
      use: debian

  - name: Create /etc/hosts
    ansible.builtin.copy:
      dest: /etc/hosts
      backup: yes
      content: |
        127.0.0.1  localhost
        {{ ansible_default_ipv4.address }}  {{ host }}.{{ domain }} {{ host }}
