---
- name: Deploy Nginx as a test instance
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Deploying Nginx container
    docker_container:
      image: nginx
      name: nginx
      hostname: nginx
      state: started
      restart: yes
      restart_policy: unless-stopped
      ports:
      - 80:80
      - 443:443
      volumes:
      - /etc/ssl:/etc/ssl

  - name: Creating an alternate default.conf with SSL enabled
    copy:
      dest: /tmp/default.conf
      force: no
      content: |
        server {
            listen 80;
            listen 443 ssl;
            server_name  {{ ansible_hostname }}.{{ ansible_domain }};
            ssl_certificate  /etc/ssl/certs/{{ ansible_hostname }}.{{ ansible_domain }}.crt;
            ssl_certificate_key  /etc/ssl/private/{{ ansible_hostname }}.{{ ansible_domain }}.key;
            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }
        }
