---
- name: Install BIND9 and configure DNS forwarding
  hosts: localhost
  connection: local
  become: true

  # The following are OpenDNS public DNS servers. They will work, but you may
  # want to change the IP addresses to your service provider's DNS instead.
  vars:
    upstream_dns:
      primary: 208.67.222.222
      secondary: 208.67.220.220

  tasks:
    - name: Install bind9
      apt:
        name: bind9
        state: latest
        
    - name: Install dnsutils
      apt:
        name: dnsutils
        state: latest
        
    - name: Verify valid starting configuration
      shell:
        cmd: named-checkconf
      register: named_checkconf
      failed_when: named_checkconf.stdout_lines | length > 0

    - name: Configure forwarders
      lineinfile:
        path: /etc/bind/named.conf.options
        insertafter: "\t// };"
        regexp: "^\tforwarders { {{ upstream_dns.primary }}; {{ upstream_dns.secondary }}; };$"
        line: "\tforwarders { {{ upstream_dns.primary }}; {{ upstream_dns.secondary }}; };\n"

    - name: Allow queries from hosts other than just localhost
      lineinfile:
        path: /etc/bind/named.conf.options
        insertbefore: "};"
        regexp: "^\tallow-query { any; };"
        line: "\tallow-query { any; };"

    - name: Verify final configuration
      shell:
        cmd: named-checkconf
      register: named_checkconf
      failed_when: named_checkconf.stdout_lines | length > 0
        
    - name: Reload BIND9 config
      systemd:
        name: bind9
        enabled: yes
        state: reloaded
        
    - name: Test DNS lookup for raspberrypi.org
      shell:
        cmd: nslookup raspberrypi.org 127.0.0.1
      register: nslookup
      failed_when: nslookup.stdout is not search("raspberrypi.org")

    - name: Report new DNS server addresses
      debug:
        msg: You may now use {{ ansible_default_ipv4.address }} as a DNS server.