---
- name: Install Docker Community Edition
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installing apt key for official repository
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg
      state: present
      
  - name: Adding official repository
    apt_repository:
      repo: deb [arch=armhf] https://download.docker.com/linux/raspbian bullseye stable

  - name: Installing Docker
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Installing Docker Compose
    shell:
      cmd: pip3 install docker-compose

  - name: Adding pi user to docker group
    user:
      name: pi
      groups: docker

  - name: Starting Docker
    systemd:
      name: docker
      enabled: yes
      state: started
