---
- name: Install OpenLDAP
  hosts: localhost
  connection: local
  become: true

  vars:
    admin_password: password

  tasks:
  - name: Pre-configuring LDAP admin password
    debconf:
      name: slapd
      question: slapd/password1
      value: "{{ admin_password }}"
      vtype: password

  - name: Confirming LDAP admin password
    debconf:
      name: slapd
      question: slapd/password2
      value: "{{ admin_password }}"
      vtype: password

  - name: Installing slapd
    apt:
      name: slapd
      state: latest
      update_cache: true

  - name: Installing lapdutils
    apt:
      name: ldap-utils
      state: latest
      update_cache: true

  - name: Reminding to change the password
    debug:
      msg: The initial password is '{{ admin_password }}'.
