---
- name: Install BIND9 and configure DNS forwarding
  hosts: localhost
  connection: local
  become: true

  # This playbook uses information gathered from the current network
  # configuration to determine what the forwarding DNS server addresses
  # should be. Check the contents of /etc/resolve.conf to see if those
  # addresses are correct.
  vars:
    upstream_dns:
      primary: "{{ ansible_dns.nameservers[0] }}"
      secondary: "{{ ansible_dns.nameservers[1] }}"

  tasks:
    - name: Installing BIND9
      apt:
        name: bind9
        state: latest
        
    - name: Installing dnsutils
      apt:
        name: dnsutils
        state: latest
        
    - name: Verifying valid starting configuration
      shell:
        cmd: named-checkconf
      register: named_checkconf
      failed_when: named_checkconf.stdout_lines | length > 0

    - name: Configuring forwarders
      lineinfile:
        path: /etc/bind/named.conf.options
        insertafter: "\t// };"
        regexp: "^\tforwarders { {{ upstream_dns.primary }}; {{ upstream_dns.secondary }}; };$"
        line: "\tforwarders { {{ upstream_dns.primary }}; {{ upstream_dns.secondary }}; };\n"

    # Allowing queried from anywhere simplifies things and on a home network,
    # the Raspberry Pi DNS server should not be accessible from the internet.
    - name: Allowing queries from hosts other than just localhost
      lineinfile:
        path: /etc/bind/named.conf.options
        insertbefore: "};"
        regexp: "^\tallow-query { any; };"
        line: "\tallow-query { any; };"

    # Errors like "got insecure response; parent indicates it should be secure"
    # will start showing up if dnssec-validation is left set to auto. You can
    # troubleshoot them or accept that for a home network, DNS security can
    # probably be a little lax.
    - name: Disabling DNSSEC
      replace:
        path: /etc/bind/named.conf.options
        regexp: "dnssec-validation auto;"
        replace: "dnssec-validation no;"

    - name: Verifying final configuration
      shell:
        cmd: named-checkconf
      register: named_checkconf
      failed_when: named_checkconf.stdout_lines | length > 0
        
    - name: Reloading BIND9 config
      systemd:
        name: bind9
        enabled: yes
        state: reloaded
        
    - name: Testing DNS lookup for raspberrypi.org
      shell:
        cmd: nslookup raspberrypi.org 127.0.0.1
      register: nslookup
      failed_when: nslookup.stdout is not search("raspberrypi.org")

    - name: Reporting new DNS server addresses
      debug:
        msg: You may now use {{ ansible_default_ipv4.address }} as a DNS server.
