---
- name: Install Cockpit web-based admin tool
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installing LVM2 support for udisks2
    apt:
      name: udisks2-lvm2
      state: latest
      update_cache: true
  
  - name: Installing Cockpit
    apt:
      name: cockpit
      state: latest

