---
- name: Run Statping as a Docker container
  hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Create a directory for Statping volume
    file:
      path: /opt/docker/statping/app
      state: directory

  - name: Run Statping
    docker_container:
      image: statping/statping
      name: statping
      hostname: statping
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        TZ: "{{ ansible_date_time.tz }}"
      ports:
      - 8080:8080
      volumes:
      - /opt/docker/statping/app:/app