---
- name: Run Node Red as a Docker container
  hosts: localhost
  connection: local
  become: true
  
  tasks:

  # Node Red runs as UID 1000, so the data directory needs the same owner.
  # Otherwise, the Node Red container will restart endlessly.
  - name: Create a directory for data
    file:
      path: /opt/docker/node-red/data
      owner: '1000'
      state: directory

  - name: Run Node Red
    docker_container:
      image: nodered/node-red
      name: node-red
      hostname: node-red
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        TZ: "{{ ansible_date_time.tz }}"
      labels:
        io.portainer.accesscontrol.teams: "Portainer Admins"
      ports:
      - 1880:1880
      volumes:
      - /opt/docker/node-red/data:/data