---
- name: Run Postgres as a Docker container.
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Ensure config and data directory exist.
    file:
      path: /opt/docker/postgres/{{ item }}
      state: directory
    with_items:
    - config
    - data

  - name: Run Postgres container.
    docker_container:
      image: postgres
      name: postgres
      hostname: postgres
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        POSTGRES_PASSWORD: password
      ports:
      - 5432:5432
      volumes:
      - /opt/docker/postgres/config:/etc/postgresql
      - /opt/docker/postgres/data:/var/lib/postgresql/data

  - name: Run pgadmin administration tool.
    docker_container:
      image: biarms/pgadmin4
      name: pgadmin
      hostname: pgadmin
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        PGADMIN_DEFAULT_PASSWORD: password
      ports:
      - 5050:5050