---
- name: Run proftpd-anon as a Docker container
  hosts: localhost
  connection: local
  become: true

  vars:
    public_ftp: /srv/ftp

  tasks:
  - name: Create a directory for anonymously accessible files
    file:
      path: "{{ public_ftp }}"
      state: directory

  # ProFTPd runs on the actual network interface (network_mode: host)
  # instead of having its ports redirected. Port mapping proved to be
  # troublesome for passive mode and not all clients do active mode.
  - name: Run ProFTPd
    docker_container:
      image: davescodemusings/proftpd-anon
      name: proftpd-anon
      hostname: proftpd-anon
      state: started
      restart: yes
      restart_policy: unless-stopped
      labels:
        io.portainer.accesscontrol.teams: "Portainer Admins"
      network_mode: host
      volumes:
      - "{{ public_ftp }}:/srv/ftp"