---
- name: Run samba-anon as a Docker container
  hosts: localhost
  connection: local
  become: true

  vars:
    samba_public_dir: /srv/public
    samba_media_dir: /srv/media
    samba_shared_dir: /srv/shared
  tasks:
  - name: Create a directory for read-only public files
    file:
      path: "{{ samba_public_dir }}"
      state: directory

  - name: Create a directory for read-only media files
    file:
      path: "{{ samba_media_dir }}"
      state: directory

  - name: Create a directory for read-write shared files
    file:
      path: "{{ samba_shared_dir }}"
      state: directory

  - name: Run samba-anon
    docker_container:
      image: davescodemusings/samba-anon
      name: samba-anon
      hostname: samba-anon
      state: started
      restart: yes
      restart_policy: unless-stopped
      labels:
        io.portainer.accesscontrol.teams: "Portainer Admins"
      ports:
      - 445:445
      volumes:
      - "{{ samba_public_dir }}:/srv/public"
      - "{{ samba_media_dir }}:/srv/media"
      - "{{ samba_shared_dir }}:/srv/shared"
