---
- name: Update System to Latest Packages
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Updating Apt cache
    apt:
      update_cache: yes

  - name: Updating all packages
    apt:
      upgrade: full

  - name: Determining the system requires a reboot
    stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Determining if any packages require a reboot
    stat:
      path: /var/run/reboot-required.pkgs
    register: reboot_required_pkgs

  - name: Advising of reboot requirement
    debug:
      msg: One or more updates require a reboot.
    when: reboot_required.stat.exists or reboot_required_pkgs.stat.exists
