---
- name: Run Gitea post-deployment tasks
  hosts: localhost
  connection: local
  become: true

  vars:
    nginx_confd_path: /opt/docker/nginx/conf.d

  tasks:
  - name: Checking for Nginx installation
    stat:
      path: "{{ nginx_confd_path }}"
    register: nginx_confd

  # The following task only runs if the Nginx conf.d directory exists.
  - name: Creating Gitea reverse proxy config
    copy:
      dest: /opt/docker/nginx/conf.d/gitea.conf
      force: no
      content: |
        # Gitea redirection and SSL off-loading using reverse proxy.
        server {
            server_name gitea.{{ ansible_hostname }}.{{ ansible_domain }};
            listen 80;
            return 301 https://gitea.{{ ansible_hostname }}.{{ ansible_domain }};
        }

        server {
            server_name gitea.{{ ansible_hostname }}.{{ ansible_domain }};
            listen 443 ssl;
            location / {
                proxy_pass http://gitea.{{ ansible_hostname }}.{{ ansible_domain }}:3000;
                proxy_set_header X-Forwarded-For $remote_addr;
            }
        }
    notify: Reloading Nginx config
    when: nginx_confd.stat.exists

  handlers:
  - name: Reloading Nginx config
    community.docker.docker_container_exec:
      container: nginx
      command: service nginx reload
