---
- name: Gitea in a Docker Container
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Create git group
    group:
      name: git
      gid: 1001

  # Creating the user account also creates /srv/git
  - name: Create git user account
    user:
      name: git
      uid: 1001
      group: git
      create_home: true
      home: /srv/git

  - name:
    file:
      path: /opt/docker/gitea
      state: directory
      owner: git
      group: pi
