services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/docker/homeassistant:/config
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mosquitto

  esphome:
    container_name: esphome
    image: esphome/esphome-armv7:latest
    ports:
      - "6052:6052"
      - "6123:6123"
    volumes:
      - /opt/docker/esphome:/config:rw
    command: config/ dashboard

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/docker/node-red:/data
    depends_on:
      - mosquitto
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/docker/mosquitto:/mosquitto
    ports:
      - "1883:1883"
