---
- name: Run NextCloud pre-deployment tasks
  hosts: localhost
  connection: local
  become: true

  tasks:
  # Homeassistant uses a SQLite database (among other options.)
  - name: Install SQLite client
    apt:
      name: sqlite3
      state: latest

  - name: Create Homeassistant configuration directory
    file:
      path: /opt/docker/homeassistant
      state: directory
      mode: '0755'
      owner: root
      group: pi

  - name: Create ESPHome configuration directory
    file:
      path: /opt/docker/esphome
      state: directory
      mode: '0755'
      owner: root
      group: pi

  - name: Create Node Red configuration directory
    file:
      path: /opt/docker/node-red
      state: directory
      mode: '0755'
      owner: pi
      group: pi

  - name: Creating Mosquitto configuration and data directories
    file:
      path: /opt/docker/mosquitto/{{ item }}
      state: directory
      mode: '0755'
      owner: root
      group: pi
    with_items:
      - config
      - data

  - name: Creating Mosquitto config file
    copy:
      dest: /opt/docker/mosquitto/config/mosquitto.conf
      force: no
      content: |
        allow_anonymous true
        listener 1883
        log_dest stdout
        password_file /mosquitto/config/mosquitto.passwd
        persistence true
        persistence_location /mosquitto/data/
