services:
    nginx:
        image: nginx
        container_name: nginx
        hostname: nginx
        restart: unless-stopped
        ports:
        - 80:80
        - 443:443
        volumes:
        - /etc/ssl:/etc/ssl:ro
        - /opt/docker/nginx/conf.d:/etc/nginx/conf.d
        - /srv/www:/usr/share/nginx/html:ro
