services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        hostname: portainer
        restart: unless-stopped
        ports:
        - 8000:8000
        - 9000:9000
        - 9443:9443
        volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
    data:
    
